.ORIG x3000
LD R2, INIT
LEA R1, BUFFER
LD R4, ASCII_ZERO
LD R5, NEG_ASCII_ZERO
LEA R0, INPUT_PROMPT
PUTS
READ_LOOP
GETC
OUT
ADD R3, R0, #-10 
BRz CONVERT 
STR R0, R1, #0 
ADD R1, R1, #1
BRnzp READ_LOOP
CONVERT
LEA R1, BUFFER 
LEA R6, ARRAY 
LD R2, INIT 
CONVERT_LOOP
LDR R0, R1, #0
ADD R0, R0, R5 
STR R0, R6, #0
ADD R1, R1, #1
ADD R6, R6, #1
ADD R2, R2, #1
ADD R3, R2, #-10
BRz BUBBLE_SORT
BRnzp CONVERT_LOOP
BUBBLE_SORT
LD R6, ARRAY_LEN 
ADD R4, R6, #0 
OUTER_LOOP
ADD R4, R4, #-1 
BRz OUTPUT_LOOP 
LEA R3, ARRAY 
ADD R5, R4, #0 
INNER_LOOP
LDR R0, R3, #0 
LDR R1, R3, #1 
NOT R2, R1
ADD R2, R2, #1
ADD R2, R0, R2 
BRN SWAP 
SKIP_SWAP
ADD R3, R3, #1 
ADD R5, R5, #-1
BRp INNER_LOOP
BRnzp OUTER_LOOP
SWAP
STR R1, R3, #0 
STR R0, R3, #1
BRnzp SKIP_SWAP
OUTPUT_LOOP
LEA R1, ARRAY
LD R2, INIT 
PRINT_LOOP
LDR R0, R1, #0 
LD R4, ASCII_ZERO
ADD R0, R0, R4 
OUT 
LEA R0, NEWLINE
PUTS 
ADD R1, R1, #1 
ADD R2, R2, #1
ADD R3, R2, #-10
BRz END
BRnzp PRINT_LOOP
END
HALT
INIT .FILL #0
INPUT_PROMPT .STRINGZ "Enter string: "
NEWLINE .STRINGZ "\n"
ASCII_ZERO .FILL #48
NEG_ASCII_ZERO .FILL #-48
ARRAY .BLKW #10
ARRAY_LEN .FILL #10
BUFFE
.END